#### Descripció
Aprèn a gestionar paràmetres amb Python.

In [171]:
import numpy as np
import pandas as pd

from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import MinMaxScaler

### Nivell 1
- **Exercici 1**

Agafa un conjunt de dades de tema esportiu que t'agradi i normalitza els atributs categòrics en dummy. Estandaritza els atributs numèrics amb StandardScaler.

Se importa un dataset con los resultados de los mundiales del League of Legends de 2021. Incluye datos catégoricos (equipos, jugadores campeones usados y resultado) y numéricos (muertes, asistencias, oro ganado, daño, etc).

In [172]:
raw_df = pd.read_csv('lol2021.csv')
raw_df

,Team,Player,Opponent,Position,Champion,Kills,Deaths,Assists,Creep Score,Gold Earned,Champion Damage Share,Kill Participation,Wards Placed,Wards Destroyed,Ward Interactions,Dragons For,Dragons Against,Barons For,Barons Against,Result
0,UOL,Boss,GS,Top,Camille,4,5,3,188,11107,0.17,0.78,8,8,16,0,4,0,1,L
1,GS,Crazy,UOL,Top,Gwen,3,1,9,217,12201,0.20,0.52,10,7,17,4,0,1,0,W
2,UOL,Ahahacik,GS,Jungle,Trundle,2,4,5,156,9048,0.15,0.78,8,14,22,0,4,0,1,L
3,GS,Mojito,UOL,Jungle,Talon,5,4,10,194,11234,0.23,0.65,12,8,20,4,0,1,0,W
4,UOL,Nomanz,GS,Mid,Leblanc,1,3,4,216,9245,0.29,0.56,6,9,15,0,4,0,1,L
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
215,BYG,Maoan,UOL,Mid,Ryze,4,4,2,356,15558,0.23,0.32,24,6,30,4,1,1,1,W
216,UOL,Argonavt,BYG,Adc,Senna,1,3,9,58,9554,0.16,0.71,35,16,51,1,4,1,1,L
217,BYG,Doggo,UOL,Adc,Draven,10,2,4,353,20546,0.38,0.74,15,5,20,4,1,1,1,W
218,UOL,Santas,BYG,Support,Wukong,0,4,7,200,10354,0.11,0.50,16,8,24,1,4,1,1,L
219,BYG,Kino,UOL,Support,Rakan,0,5,9,41,9304,0.06,0.47,49,15,64,4,1,1,1,W

Se normaliza los datos de muertes y torretas contruidas

In [173]:
ss = StandardScaler()

Xstd = ss.fit_transform(raw_df[['Kills', 'Wards Placed']].values)
Xstd

array([[ 0.50155703, -0.73062203],
       [ 0.11302694, -0.6030531 ],
       [-0.27550316, -0.73062203],
       [ 0.89008713, -0.47548418],
       [-0.66403326, -0.85819095],
       [ 0.89008713, -0.15656186],
       [-0.66403326, -0.79440649],
       [ 2.44420752, -0.28413079],
       [-0.66403326,  1.31048078],
       [-1.05256335,  1.05534293],
       [-0.66403326, -0.6030531 ],
       [-0.66403326, -0.34791525],
       [-0.66403326, -0.53926864],
       [-1.05256335, -0.53926864],
       [-0.66403326, -0.66683756],
       [ 2.05567742, -0.6030531 ],
       [-0.66403326, -0.73062203],
       [ 0.11302694, -0.41169971],
       [-1.05256335,  1.62940309],
       [-0.66403326,  1.88454094],
       [ 1.27861723, -0.79440649],
       [-0.66403326, -0.41169971],
       [ 0.89008713, -0.41169971],
       [ 0.11302694, -0.41169971],
       [-1.05256335, -0.22034633],
       [-0.27550316, -0.0927774 ],
       [ 0.89008713, -0.22034633],
       [ 0.11302694, -0.34791525],
       [-0.66403326,  2.6499545 ],
       [-1.05256335,  2.58617003],
       [ 0.50155703, -0.47548418],
       [-0.66403326, -0.28413079],
       [-1.05256335,  0.09857599],
       [ 1.27861723, -0.28413079],
       [-0.66403326, -0.34791525],
       [ 0.50155703, -0.85819095],
       [-0.27550316, -0.41169971],
       [ 1.66714733, -0.41169971],
       [-1.05256335,  2.33103218],
       [-0.66403326,  3.03266127],
       [ 0.89008713, -0.47548418],
       [ 0.11302694, -0.41169971],
       [-0.66403326, -0.22034633],
       [-0.27550316, -0.6030531 ],
       [-0.66403326, -0.22034633],
       [-0.27550316, -0.0927774 ],
       [ 0.50155703, -0.28413079],
       [-0.66403326, -0.02899294],
       [-0.66403326,  1.94832541],
       [-1.05256335,  1.75697202],
       [ 2.05567742, -0.92197542],
       [-0.27550316, -0.41169971],
       [ 0.50155703, -0.85819095],
       [-0.66403326, -0.98575988],
       [-0.27550316, -0.92197542],
       [-1.05256335, -0.34791525],
       [-0.66403326, -0.47548418],
       [-0.27550316, -0.47548418],
       [-1.05256335,  0.927774  ],
       [-1.05256335,  0.80020508],
       [-0.66403326, -0.41169971],
       [-0.27550316, -0.15656186],
       [-0.66403326, -0.02899294],
       [-1.05256335, -0.28413079],
       [-1.05256335,  0.22614491],
       [ 0.89008713, -0.0927774 ],
       [ 0.50155703, -0.22034633],
       [ 1.66714733,  0.09857599],
       [-1.05256335,  1.50183417],
       [-0.66403326,  1.88454094],
       [-1.05256335, -0.28413079],
       [ 1.27861723, -0.0927774 ],
       [-1.05256335,  0.16236045],
       [-0.66403326, -0.47548418],
       [-0.66403326, -0.34791525],
       [-0.27550316, -0.6030531 ],
       [ 0.11302694,  0.22614491],
       [ 1.66714733, -0.34791525],
       [-0.66403326,  3.03266127],
       [-0.27550316,  4.62727284],
       [ 0.50155703, -0.6030531 ],
       [ 0.11302694, -0.73062203],
       [ 1.66714733, -0.53926864],
       [-0.66403326, -0.79440649],
       [ 0.89008713, -0.6030531 ],
       [ 0.11302694, -0.34791525],
       [ 1.27861723, -0.47548418],
       [-0.27550316, -0.41169971],
       [-1.05256335,  2.07589433],
       [-1.05256335,  1.24669632],
       [ 0.89008713, -0.6030531 ],
       [ 0.50155703, -0.79440649],
       [ 0.89008713, -0.85819095],
       [-1.05256335, -0.66683756],
       [-0.66403326, -0.6030531 ],
       [-0.66403326, -1.04954434],
       [ 2.05567742, -0.66683756],
       [-0.66403326, -0.73062203],
       [-1.05256335,  0.80020508],
       [-1.05256335,  0.73642062],
       [-1.05256335, -0.47548418],
       [ 0.50155703, -0.47548418],
       [-1.05256335, -0.34791525],
       [ 0.89008713, -0.6030531 ],
       [-1.05256335, -0.41169971],
       [-0.66403326, -0.28413079],
       [-1.05256335, -0.53926864],
       [ 0.50155703, -0.53926864],
       [-0.27550316,  1.75697202],
       [ 0.11302694,  0.99155847],
       [ 0.11302694, -0.0927774 ],
       [ 0.50155703, -0.34791525],
       [ 0.50155703, -0.6030531 ],
       [ 0.50155703, -0.0927774 ],
       [-0.27550316, -0.66683756],
       [ 1.27861723, -0.15656186],
       [ 1.66714733, -0.28413079],
       [ 2.44420752, -0.28413079],
       [-1.05256335,  2.71373896],
       [ 0.11302694,  2.90509235],
       [ 0.11302694, -0.28413079],
       [ 0.50155703, -0.53926864],
       [-0.66403326, -0.53926864],
       [ 0.50155703, -0.34791525],
       [ 0.11302694, -0.47548418],
       [-0.66403326, -0.6030531 ],
       [-0.27550316, -0.28413079],
       [ 2.44420752, -0.28413079],
       [-0.66403326,  1.50183417],
       [ 0.11302694,  1.24669632],
       [ 3.99832791, -0.47548418],
       [ 0.50155703, -0.02899294],
       [-0.66403326, -0.15656186],
       [ 2.05567742, -0.92197542],
       [-0.66403326,  0.09857599],
       [ 1.27861723, -0.28413079],
       [-0.27550316, -0.28413079],
       [ 0.11302694, -0.53926864],
       [-1.05256335,  2.71373896],
       [-1.05256335,  3.1602302 ],
       [-1.05256335, -0.41169971],
       [ 0.50155703, -0.47548418],
       [-0.66403326, -0.53926864],
       [ 0.11302694, -0.79440649],
       [-0.66403326, -0.22034633],
       [-0.27550316, -0.34791525],
       [-0.27550316,  0.03479153],
       [ 1.27861723, -0.41169971],
       [-0.66403326,  1.11912739],
       [-1.05256335,  1.94832541],
       [-1.05256335, -0.22034633],
       [ 0.50155703, -0.41169971],
       [ 0.50155703, -0.85819095],
       [ 2.05567742, -0.47548418],
       [-0.66403326, -0.41169971],
       [ 0.11302694, -0.22034633],
       [-0.66403326, -0.47548418],
       [ 1.27861723, -0.0927774 ],
       [-1.05256335,  1.82075648],
       [-1.05256335,  2.01210987],
       [ 0.50155703, -0.66683756],
       [ 1.27861723, -0.6030531 ],
       [-0.66403326, -0.92197542],
       [ 0.11302694, -0.53926864],
       [ 0.11302694, -0.79440649],
       [ 1.27861723, -0.85819095],
       [-0.27550316, -0.6030531 ],
       [-0.27550316,  0.16236045],
       [-0.66403326,  0.80020508],
       [-0.27550316, -0.53926864],
       [ 2.83273762, -0.73062203],
       [-0.66403326, -0.34791525],
       [ 0.50155703, -0.41169971],
       [-1.05256335, -0.41169971],
       [-0.66403326, -0.34791525],
       [-0.27550316, -0.73062203],
       [ 1.66714733, -0.6030531 ],
       [-0.66403326, -0.22034633],
       [-1.05256335,  1.75697202],
       [-1.05256335,  1.37426524],
       [ 1.66714733, -0.02899294],
       [ 0.11302694, -0.53926864],
       [-0.27550316, -1.04954434],
       [ 0.50155703, -0.53926864],
       [ 2.05567742, -0.28413079],
       [-0.66403326, -0.34791525],
       [ 2.05567742, -0.47548418],
       [-0.66403326, -0.47548418],
       [-1.05256335,  1.56561863],
       [-1.05256335,  0.927774  ],
       [ 2.05567742, -0.85819095],
       [-0.66403326, -0.73062203],
       [ 1.66714733, -0.92197542],
       [-0.66403326, -0.92197542],
       [ 0.11302694, -0.66683756],
       [-0.66403326, -0.47548418],
       [-0.27550316, -0.66683756],
       [-1.05256335, -0.53926864],
       [-0.66403326,  0.80020508],
       [-1.05256335,  1.24669632],
       [ 0.11302694, -0.66683756],
       [-0.27550316, -0.0927774 ],
       [ 0.89008713, -0.34791525],
       [ 1.66714733, -0.66683756],
       [ 1.27861723, -0.15656186],
       [-1.05256335, -0.22034633],
       [ 1.27861723, -0.6030531 ],
       [-0.27550316, -0.47548418],
       [-1.05256335,  2.84130788],
       [-0.66403326,  2.45860111],
       [ 0.89008713, -0.15656186],
       [ 0.50155703, -0.41169971],
       [ 0.11302694, -0.02899294],
       [-0.66403326, -0.79440649],
       [ 0.89008713, -0.53926864],
       [ 0.50155703,  0.28992938],
       [-0.66403326,  0.99155847],
       [ 2.83273762, -0.28413079],
       [-1.05256335, -0.22034633],
       [-1.05256335,  1.88454094]])

In [174]:
print (Xstd.mean())
print (Xstd.std())

5.652044489000796e-17
1.0

In [175]:
x = raw_df[['Kills', 'Creep Score', 'Gold Earned']]
mms = MinMaxScaler()
Xn = mms.fit_transform(x)

In [176]:
Xn.min(axis=0)

array([0., 0., 0.])

In [177]:
Xn.max(axis=0)

array([1., 1., 1.])

Se muestra un nuevo DF con los datos categórigos tratados con libreria Dummie, generando nuevas columnas para los equipos y los resultados del torneo.

In [178]:
dummies = pd.get_dummies(raw_df, columns=["Team", "Result"])

print("Original DataFrame:")
raw_df

Original DataFrame:

,Team,Player,Opponent,Position,Champion,Kills,Deaths,Assists,Creep Score,Gold Earned,Champion Damage Share,Kill Participation,Wards Placed,Wards Destroyed,Ward Interactions,Dragons For,Dragons Against,Barons For,Barons Against,Result
0,UOL,Boss,GS,Top,Camille,4,5,3,188,11107,0.17,0.78,8,8,16,0,4,0,1,L
1,GS,Crazy,UOL,Top,Gwen,3,1,9,217,12201,0.20,0.52,10,7,17,4,0,1,0,W
2,UOL,Ahahacik,GS,Jungle,Trundle,2,4,5,156,9048,0.15,0.78,8,14,22,0,4,0,1,L
3,GS,Mojito,UOL,Jungle,Talon,5,4,10,194,11234,0.23,0.65,12,8,20,4,0,1,0,W
4,UOL,Nomanz,GS,Mid,Leblanc,1,3,4,216,9245,0.29,0.56,6,9,15,0,4,0,1,L
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
215,BYG,Maoan,UOL,Mid,Ryze,4,4,2,356,15558,0.23,0.32,24,6,30,4,1,1,1,W
216,UOL,Argonavt,BYG,Adc,Senna,1,3,9,58,9554,0.16,0.71,35,16,51,1,4,1,1,L
217,BYG,Doggo,UOL,Adc,Draven,10,2,4,353,20546,0.38,0.74,15,5,20,4,1,1,1,W
218,UOL,Santas,BYG,Support,Wukong,0,4,7,200,10354,0.11,0.50,16,8,24,1,4,1,1,L
219,BYG,Kino,UOL,Support,Rakan,0,5,9,41,9304,0.06,0.47,49,15,64,4,1,1,1,W

In [179]:
print("DataFrame with Dummies:")
dummies

DataFrame with Dummies:

,Player,Opponent,Position,Champion,Kills,Deaths,Assists,Creep Score,Gold Earned,Champion Damage Share,...,Team_DFM,Team_GS,Team_HLE,Team_INF,Team_LNG,Team_PCE,Team_RED,Team_UOL,Result_L,Result_W
0,Boss,GS,Top,Camille,4,5,3,188,11107,0.17,...,0,0,0,0,0,0,0,1,1,0
1,Crazy,UOL,Top,Gwen,3,1,9,217,12201,0.20,...,0,1,0,0,0,0,0,0,0,1
2,Ahahacik,GS,Jungle,Trundle,2,4,5,156,9048,0.15,...,0,0,0,0,0,0,0,1,1,0
3,Mojito,UOL,Jungle,Talon,5,4,10,194,11234,0.23,...,0,1,0,0,0,0,0,0,0,1
4,Nomanz,GS,Mid,Leblanc,1,3,4,216,9245,0.29,...,0,0,0,0,0,0,0,1,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
215,Maoan,UOL,Mid,Ryze,4,4,2,356,15558,0.23,...,0,0,0,0,0,0,0,0,0,1
216,Argonavt,BYG,Adc,Senna,1,3,9,58,9554,0.16,...,0,0,0,0,0,0,0,1,1,0
217,Doggo,UOL,Adc,Draven,10,2,4,353,20546,0.38,...,0,0,0,0,0,0,0,0,0,1
218,Santas,BYG,Support,Wukong,0,4,7,200,10354,0.11,...,0,0,0,0,0,0,0,1,1,0
219,Kino,UOL,Support,Rakan,0,5,9,41,9304,0.06,...,0,0,0,0,0,0,0,0,0,1

### Nivell 2
- **Exercici 2**

Continua amb el conjunt de dades de tema esportiu que t'agradi i aplica l'anàlisi de components principals.

### Nivell 3
- **Exercici 3**

Continua amb el conjunt de dades de tema esportiu que t'agradi i normalitza les dades tenint en compte els outliers.